### ISSUE TITLE
Having time. sleep() for debugging in the merged project code - not good practice

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [Zergoks/InternalEducation#11]
https://github.com/Zergoks/InternalEducation/blob/a800e1f3095545e0d1e90cacc09db9d45377a906/Core/utils.py#L23
`time. sleep()` should not be in the merged project code, only during debugging. The next issue - creating a method for a method.

**Comment by Zergoks** [comment]
@ValeryiaLukyanava 
1. About sleep in code. We talked about this issue a few weeks ago. The problem is visibility and presence of element detected by selenium but the element can't be clicked yet. So 'until' condition return True but failed on click stage. Still thinking (and maybe you can help me) about solution. The native idea is something like 'wait until page fully load' and this solution have cons (e.g. time consuming, lazy loading, etc).
2. Method for method used as reference. When the above problem is solved, it will help to indicate the tests where the changes should also be applied.

**Comment by ValeryiaLukyanava** [comment]
I can't find code usage of `explicit_sleep()`. 
@Zergoks What web element are you waiting for? And in what browser do have this issue?

**Comment by Zergoks** [comment]
![InternalEducation – utils py 2021-06-23 12 29 42](https://user-images.githubusercontent.com/58077496/123073192-df931d80-d41e-11eb-88f8-999fc7247010.png)
because of usage: import explicit_sleep as sleep

**Comment by ValeryiaLukyanava** [comment]
Please, look at: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState
Try smth like this:
`wait.until(lambda driver: self.driver.execute_script('return document.readyState') == 'complete')`
@Zergoks  And then, please, notify me about your results.

**Comment by Zergoks** [comment]
@ValeryiaLukyanava 
Works fine for me. Also save few seconds for this particular SUT. I appreciate your time, thanks

**Comment by ValeryiaLukyanava** [comment]
Awesome! :star_struck:
